# Generated by Django 3.2.3 on 2022-09-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220925_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='discource',
            name='articel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
