# Generated by Django 3.2.3 on 2022-09-25 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
