branch-defaults:
  main:
    environment: carbonized
    group_suffix: null
environment-defaults:
  carbonized:
    branch: null
    repository: null
global:
  application_name: BE
  branch: null
  default_ec2_keyname: carbonized
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
