# Generated by Django 3.2.3 on 2022-09-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_discource'),
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Discource',
            field=models.ManyToManyField(blank=True, null=True, to='articles.Discource'),
        ),
    ]
